---
title: "World Bank Population Analysis"
author: "Allison Horst"
date: "9/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

## Read in data

```{r}
wb_pop <- read_csv(here("data","world_bank_pop.csv"))
```

## Make it tidy

- pivot_longer()

```{r}
wb_pop_long <- wb_pop %>% 
  pivot_longer(cols = '2000':'2017',
               names_to = "year",
               values_to = "population")
```

Now split the indicator column into 2 separate variables

```{r}
wb_pop_tidy <- wb_pop_long %>% 
  pivot_wider(names_from = indicator,
              values_from = population) %>% 
  clean_names() %>% 
  mutate(year = as.numeric(year))
```

## Make a graph for countries w/top5 populations in 2020

```{r}
top5_pop <- wb_pop_tidy %>% 
  filter(country %in% c("CHN", "IND", "USA", "IDN", "BRA"))
```

```{r}
ggplot(data = top5_pop, aes(x = year, y = total_population)) +
  geom_line(aes(color = country))
```

